##
##  Apache Makefile, automatically generated by Configure script.
##  Hand-edited changes will be lost if the Configure script is re-run.
##  Sources: - ../../Makefile.config (via Configuration.apaci)
##           - ./Makefile.tmpl
##

##
##  Inherited Makefile options from Configure script
##  (Begin of automatically generated section)
##
SRCDIR=../..
#EXTRA_CFLAGS=`$(SRCDIR)/apaci`
OSDIR=$(SRCDIR)/os/unix
INCDIR= -I$(SRCDIR)/include
INCLUDES0=-I$(OSDIR) -I$(INCDIR)
SHELL=/bin/sh
OS=FreeBSD 5.4-RELEASE
CC=gcc 
CPP=gcc -E
TARGET=httpd
CFLAGS1= -funsigned-char -DUSE_EXPAT -I$(SRCDIR)/lib/expat-lite -DNO_DL_NEEDED
RANLIB=ranlib
LIBS1=  -lcrypt

CFLAGS=$(OPTIM) $(CFLAGS1) $(EXTRA_CFLAGS)
LIBS=$(EXTRA_LIBS) $(LIBS1)
INCLUDES=$(INCLUDES1) $(INCLUDES0) $(EXTRA_INCLUDES)
LDFLAGS=$(LDFLAGS1) $(EXTRA_LDFLAGS)


LIB20_DIR = ./lib20
PUBLIC_DIR  = ./public
UNION_DIR = ./union
FORUM_DIR = ./forum
SYS_DIR = ./sys
BIN_DIR = .

MYSQL_INC = -I/usr/local/mysql5/include/mysql
INCDIR= -I$(SRCDIR)/include -I$(SRCDIR)/srclib/apr/include -I$(SRCDIR)/srclib/apr-util/include \
		 	-I$(LIB20_DIR)/apreq -I$(LIB20_DIR)/template4c -I$(LIB20_DIR)/custom -I$(PUBLIC_DIR) \
		 	-I$(UNION_DIR) -I$(FORUM_DIR) -I$(SYS_DIR) $(MYSQL_INC)


PUBLIC_OBJS = $(PUBLIC_DIR)/fun_cfg.o $(PUBLIC_DIR)/fun_public.o
UNION_OBJS = $(UNION_DIR)/fun_union_interface.o $(UNION_DIR)/fun_union_login.o \
				 $(UNION_DIR)/fun_union_reg.o $(UNION_DIR)/fun_union_my.o \
				 $(UNION_DIR)/fun_union_profile.o $(UNION_DIR)/fun_union_pwd.o 

FORUM_OBJS = $(FORUM_DIR)/fun_forum_interface.o $(FORUM_DIR)/fun_forum_index.o \
	     $(FORUM_DIR)/fun_forum_public.o $(FORUM_DIR)/fun_forum_board.o \
	     $(FORUM_DIR)/fun_forum_topic.o $(FORUM_DIR)/fun_forum_post.o \
	     $(FORUM_DIR)/fun_forum_read.o $(FORUM_DIR)/fun_forum_search.o \
	     $(FORUM_DIR)/fun_forum_manage.o

SYS_OBJS = $(SYS_DIR)/fun_sys_interface.o $(SYS_DIR)/fun_sys_editboard.o $(SYS_DIR)/fun_sys_cats.o

MYSQL_LIB = -L/usr/local/mysql/lib -lmysqlclient
#MYSQL_LIB = /usr/local/mysql/lib/libmysqlclient.a

ThirdLibs = $(PUBLIC_OBJS) $(UNION_OBJS) $(FORUM_OBJS) $(SYS_OBJS) \
				$(LIB20_DIR)/template4c/libtpllib.a $(LIB20_DIR)/custom/libcustom.a $(LIB20_DIR)/apreq/libapreq.a \
				$(MYSQL_LIB)

MODULE_NAME = mod_aforum

OBJS = $(MODULE_NAME).o


############# build module ################

all: $(MODULE_NAME).so

.c.o:
	$(CC) -fpic -c -o $@ $*.c -I. $(INCLUDES) $(INCDIR) $(CFLAGS)

$(MODULE_NAME).so:$(OBJS)
	$(CC) -shared -o $(MODULE_NAME).so $(OBJS) $(ThirdLibs)

############ module install and clear #######

install:
	cp -f $(MODULE_NAME).so /usr/local/apache2/modules/

clean:
	rm -f *.o;
	rm -f $(MODULE_NAME).so


