all: apreq.lib template4c.lib custom.lib

apreq.lib:
	make -C apreq

template4c.lib:
	make -C template4c

custom.lib:
	make -C custom


clean:
	make -C apreq clean
	make -C template4c clean
	make -C custom clean